//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.296
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PbProject.Logic.w_TodayService {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="w_TodayService.WTodayServiceSoap")]
    public interface WTodayServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetRateListByPNR", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetRateListByPNR(string username, string pnrCode, string PnrInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateOrderByPNR", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet CreateOrderByPNR(string username, string pnrCode, string rateid, string dotnum, string newRateId, string PnrInfo, string rateWay);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetOrderInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetOrderInfo(string username, string orderno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AutoPayOrder", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet AutoPayOrder(string username, string orderno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TuiFeiOrder", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet TuiFeiOrder(string username, string type, string orderno, string Repeal, string personName, string isCancelSeat, string Cause, string Remarks, string Rnum, string TicketNo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WTodayServiceSoapChannel : PbProject.Logic.w_TodayService.WTodayServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WTodayServiceSoapClient : System.ServiceModel.ClientBase<PbProject.Logic.w_TodayService.WTodayServiceSoap>, PbProject.Logic.w_TodayService.WTodayServiceSoap {
        
        public WTodayServiceSoapClient() {
        }
        
        public WTodayServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WTodayServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WTodayServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WTodayServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetRateListByPNR(string username, string pnrCode, string PnrInfo) {
            return base.Channel.GetRateListByPNR(username, pnrCode, PnrInfo);
        }
        
        public System.Data.DataSet CreateOrderByPNR(string username, string pnrCode, string rateid, string dotnum, string newRateId, string PnrInfo, string rateWay) {
            return base.Channel.CreateOrderByPNR(username, pnrCode, rateid, dotnum, newRateId, PnrInfo, rateWay);
        }
        
        public System.Data.DataSet GetOrderInfo(string username, string orderno) {
            return base.Channel.GetOrderInfo(username, orderno);
        }
        
        public System.Data.DataSet AutoPayOrder(string username, string orderno) {
            return base.Channel.AutoPayOrder(username, orderno);
        }
        
        public System.Data.DataSet TuiFeiOrder(string username, string type, string orderno, string Repeal, string personName, string isCancelSeat, string Cause, string Remarks, string Rnum, string TicketNo) {
            return base.Channel.TuiFeiOrder(username, type, orderno, Repeal, personName, isCancelSeat, Cause, Remarks, Rnum, TicketNo);
        }
    }
}
