//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.296
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PbProject.Logic.w_BTWebService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://203.88.210.234:114/BaiTuoWeb.asmx", ConfigurationName="w_BTWebService.BaiTuoWebSoap")]
    public interface BaiTuoWebSoap {
        
        // CODEGEN: 命名空间 http://203.88.210.234:114/BaiTuoWeb.asmx 的元素名称 TripType 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://203.88.210.234:114/BaiTuoWeb.asmx/GetAlterDomesticCabinZRateByParam", ReplyAction="*")]
        PbProject.Logic.w_BTWebService.GetAlterDomesticCabinZRateByParamResponse GetAlterDomesticCabinZRateByParam(PbProject.Logic.w_BTWebService.GetAlterDomesticCabinZRateByParamRequest request);
        
        // CODEGEN: 命名空间 http://203.88.210.234:114/BaiTuoWeb.asmx 的元素名称 xmlMessage 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://203.88.210.234:114/BaiTuoWeb.asmx/GetAlterDomesticCabinZRateByXml", ReplyAction="*")]
        PbProject.Logic.w_BTWebService.GetAlterDomesticCabinZRateByXmlResponse GetAlterDomesticCabinZRateByXml(PbProject.Logic.w_BTWebService.GetAlterDomesticCabinZRateByXmlRequest request);
        
        // CODEGEN: 命名空间 http://203.88.210.234:114/BaiTuoWeb.asmx 的元素名称 xmlMessage 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://203.88.210.234:114/BaiTuoWeb.asmx/GetDomesticMatchNormalZRateList", ReplyAction="*")]
        PbProject.Logic.w_BTWebService.GetDomesticMatchNormalZRateListResponse GetDomesticMatchNormalZRateList(PbProject.Logic.w_BTWebService.GetDomesticMatchNormalZRateListRequest request);
        
        // CODEGEN: 命名空间 http://203.88.210.234:114/BaiTuoWeb.asmx 的元素名称 xmlMessage 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://203.88.210.234:114/BaiTuoWeb.asmx/GetDomesticMatchNormalZRateStr", ReplyAction="*")]
        PbProject.Logic.w_BTWebService.GetDomesticMatchNormalZRateStrResponse GetDomesticMatchNormalZRateStr(PbProject.Logic.w_BTWebService.GetDomesticMatchNormalZRateStrRequest request);
        
        // CODEGEN: 命名空间 http://203.88.210.234:114/BaiTuoWeb.asmx 的元素名称 xmlElement 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://203.88.210.234:114/BaiTuoWeb.asmx/GetInvalidationProviderListXML", ReplyAction="*")]
        PbProject.Logic.w_BTWebService.GetInvalidationProviderListXMLResponse GetInvalidationProviderListXML(PbProject.Logic.w_BTWebService.GetInvalidationProviderListXMLRequest request);
        
        // CODEGEN: 命名空间 http://203.88.210.234:114/BaiTuoWeb.asmx 的元素名称 xmlDoc 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://203.88.210.234:114/BaiTuoWeb.asmx/GetInvalidationProviderListSTR", ReplyAction="*")]
        PbProject.Logic.w_BTWebService.GetInvalidationProviderListSTRResponse GetInvalidationProviderListSTR(PbProject.Logic.w_BTWebService.GetInvalidationProviderListSTRRequest request);
        
        // CODEGEN: 命名空间 http://203.88.210.234:114/BaiTuoWeb.asmx 的元素名称 xeMessage 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://203.88.210.234:114/BaiTuoWeb.asmx/pnrCreateOrderEx", ReplyAction="*")]
        PbProject.Logic.w_BTWebService.pnrCreateOrderExResponse pnrCreateOrderEx(PbProject.Logic.w_BTWebService.pnrCreateOrderExRequest request);
        
        // CODEGEN: 命名空间 http://203.88.210.234:114/BaiTuoWeb.asmx 的元素名称 xeMessage 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://203.88.210.234:114/BaiTuoWeb.asmx/pnrCreateOrderExStr", ReplyAction="*")]
        PbProject.Logic.w_BTWebService.pnrCreateOrderExStrResponse pnrCreateOrderExStr(PbProject.Logic.w_BTWebService.pnrCreateOrderExStrRequest request);
        
        // CODEGEN: 命名空间 http://203.88.210.234:114/BaiTuoWeb.asmx 的元素名称 xmlMessage 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://203.88.210.234:114/BaiTuoWeb.asmx/getOrderInfoXml", ReplyAction="*")]
        PbProject.Logic.w_BTWebService.getOrderInfoXmlResponse getOrderInfoXml(PbProject.Logic.w_BTWebService.getOrderInfoXmlRequest request);
        
        // CODEGEN: 命名空间 http://203.88.210.234:114/BaiTuoWeb.asmx 的元素名称 XmlMessage 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://203.88.210.234:114/BaiTuoWeb.asmx/NotifyXml", ReplyAction="*")]
        PbProject.Logic.w_BTWebService.NotifyXmlResponse NotifyXml(PbProject.Logic.w_BTWebService.NotifyXmlRequest request);
        
        // CODEGEN: 命名空间 http://203.88.210.234:114/BaiTuoWeb.asmx 的元素名称 Message 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://203.88.210.234:114/BaiTuoWeb.asmx/NotifyStr", ReplyAction="*")]
        PbProject.Logic.w_BTWebService.NotifyStrResponse NotifyStr(PbProject.Logic.w_BTWebService.NotifyStrRequest request);
        
        // CODEGEN: 命名空间 http://203.88.210.234:114/BaiTuoWeb.asmx 的元素名称 xml 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://203.88.210.234:114/BaiTuoWeb.asmx/ApplyRefundOrder", ReplyAction="*")]
        PbProject.Logic.w_BTWebService.ApplyRefundOrderResponse ApplyRefundOrder(PbProject.Logic.w_BTWebService.ApplyRefundOrderRequest request);
        
        // CODEGEN: 命名空间 http://203.88.210.234:114/BaiTuoWeb.asmx 的元素名称 Message 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://203.88.210.234:114/BaiTuoWeb.asmx/ApplyRefundOrderStr", ReplyAction="*")]
        PbProject.Logic.w_BTWebService.ApplyRefundOrderStrResponse ApplyRefundOrderStr(PbProject.Logic.w_BTWebService.ApplyRefundOrderStrRequest request);
        
        // CODEGEN: 命名空间 http://203.88.210.234:114/BaiTuoWeb.asmx 的元素名称 url 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://203.88.210.234:114/BaiTuoWeb.asmx/GetUrlData", ReplyAction="*")]
        PbProject.Logic.w_BTWebService.GetUrlDataResponse GetUrlData(PbProject.Logic.w_BTWebService.GetUrlDataRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAlterDomesticCabinZRateByParamRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAlterDomesticCabinZRateByParam", Namespace="http://203.88.210.234:114/BaiTuoWeb.asmx", Order=0)]
        public PbProject.Logic.w_BTWebService.GetAlterDomesticCabinZRateByParamRequestBody Body;
        
        public GetAlterDomesticCabinZRateByParamRequest() {
        }
        
        public GetAlterDomesticCabinZRateByParamRequest(PbProject.Logic.w_BTWebService.GetAlterDomesticCabinZRateByParamRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://203.88.210.234:114/BaiTuoWeb.asmx")]
    public partial class GetAlterDomesticCabinZRateByParamRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string TripType;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string TicketType;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string CoAgentOffice;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string CoUserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string CoUserPwd;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string RQStartDateTime;
        
        public GetAlterDomesticCabinZRateByParamRequestBody() {
        }
        
        public GetAlterDomesticCabinZRateByParamRequestBody(string TripType, string TicketType, string CoAgentOffice, string CoUserName, string CoUserPwd, string RQStartDateTime) {
            this.TripType = TripType;
            this.TicketType = TicketType;
            this.CoAgentOffice = CoAgentOffice;
            this.CoUserName = CoUserName;
            this.CoUserPwd = CoUserPwd;
            this.RQStartDateTime = RQStartDateTime;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAlterDomesticCabinZRateByParamResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAlterDomesticCabinZRateByParamResponse", Namespace="http://203.88.210.234:114/BaiTuoWeb.asmx", Order=0)]
        public PbProject.Logic.w_BTWebService.GetAlterDomesticCabinZRateByParamResponseBody Body;
        
        public GetAlterDomesticCabinZRateByParamResponse() {
        }
        
        public GetAlterDomesticCabinZRateByParamResponse(PbProject.Logic.w_BTWebService.GetAlterDomesticCabinZRateByParamResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://203.88.210.234:114/BaiTuoWeb.asmx")]
    public partial class GetAlterDomesticCabinZRateByParamResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement GetAlterDomesticCabinZRateByParamResult;
        
        public GetAlterDomesticCabinZRateByParamResponseBody() {
        }
        
        public GetAlterDomesticCabinZRateByParamResponseBody(System.Xml.Linq.XElement GetAlterDomesticCabinZRateByParamResult) {
            this.GetAlterDomesticCabinZRateByParamResult = GetAlterDomesticCabinZRateByParamResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAlterDomesticCabinZRateByXmlRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAlterDomesticCabinZRateByXml", Namespace="http://203.88.210.234:114/BaiTuoWeb.asmx", Order=0)]
        public PbProject.Logic.w_BTWebService.GetAlterDomesticCabinZRateByXmlRequestBody Body;
        
        public GetAlterDomesticCabinZRateByXmlRequest() {
        }
        
        public GetAlterDomesticCabinZRateByXmlRequest(PbProject.Logic.w_BTWebService.GetAlterDomesticCabinZRateByXmlRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://203.88.210.234:114/BaiTuoWeb.asmx")]
    public partial class GetAlterDomesticCabinZRateByXmlRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement xmlMessage;
        
        public GetAlterDomesticCabinZRateByXmlRequestBody() {
        }
        
        public GetAlterDomesticCabinZRateByXmlRequestBody(System.Xml.Linq.XElement xmlMessage) {
            this.xmlMessage = xmlMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAlterDomesticCabinZRateByXmlResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAlterDomesticCabinZRateByXmlResponse", Namespace="http://203.88.210.234:114/BaiTuoWeb.asmx", Order=0)]
        public PbProject.Logic.w_BTWebService.GetAlterDomesticCabinZRateByXmlResponseBody Body;
        
        public GetAlterDomesticCabinZRateByXmlResponse() {
        }
        
        public GetAlterDomesticCabinZRateByXmlResponse(PbProject.Logic.w_BTWebService.GetAlterDomesticCabinZRateByXmlResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://203.88.210.234:114/BaiTuoWeb.asmx")]
    public partial class GetAlterDomesticCabinZRateByXmlResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement GetAlterDomesticCabinZRateByXmlResult;
        
        public GetAlterDomesticCabinZRateByXmlResponseBody() {
        }
        
        public GetAlterDomesticCabinZRateByXmlResponseBody(System.Xml.Linq.XElement GetAlterDomesticCabinZRateByXmlResult) {
            this.GetAlterDomesticCabinZRateByXmlResult = GetAlterDomesticCabinZRateByXmlResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDomesticMatchNormalZRateListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDomesticMatchNormalZRateList", Namespace="http://203.88.210.234:114/BaiTuoWeb.asmx", Order=0)]
        public PbProject.Logic.w_BTWebService.GetDomesticMatchNormalZRateListRequestBody Body;
        
        public GetDomesticMatchNormalZRateListRequest() {
        }
        
        public GetDomesticMatchNormalZRateListRequest(PbProject.Logic.w_BTWebService.GetDomesticMatchNormalZRateListRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://203.88.210.234:114/BaiTuoWeb.asmx")]
    public partial class GetDomesticMatchNormalZRateListRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement xmlMessage;
        
        public GetDomesticMatchNormalZRateListRequestBody() {
        }
        
        public GetDomesticMatchNormalZRateListRequestBody(System.Xml.Linq.XElement xmlMessage) {
            this.xmlMessage = xmlMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDomesticMatchNormalZRateListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDomesticMatchNormalZRateListResponse", Namespace="http://203.88.210.234:114/BaiTuoWeb.asmx", Order=0)]
        public PbProject.Logic.w_BTWebService.GetDomesticMatchNormalZRateListResponseBody Body;
        
        public GetDomesticMatchNormalZRateListResponse() {
        }
        
        public GetDomesticMatchNormalZRateListResponse(PbProject.Logic.w_BTWebService.GetDomesticMatchNormalZRateListResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://203.88.210.234:114/BaiTuoWeb.asmx")]
    public partial class GetDomesticMatchNormalZRateListResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement GetDomesticMatchNormalZRateListResult;
        
        public GetDomesticMatchNormalZRateListResponseBody() {
        }
        
        public GetDomesticMatchNormalZRateListResponseBody(System.Xml.Linq.XElement GetDomesticMatchNormalZRateListResult) {
            this.GetDomesticMatchNormalZRateListResult = GetDomesticMatchNormalZRateListResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDomesticMatchNormalZRateStrRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDomesticMatchNormalZRateStr", Namespace="http://203.88.210.234:114/BaiTuoWeb.asmx", Order=0)]
        public PbProject.Logic.w_BTWebService.GetDomesticMatchNormalZRateStrRequestBody Body;
        
        public GetDomesticMatchNormalZRateStrRequest() {
        }
        
        public GetDomesticMatchNormalZRateStrRequest(PbProject.Logic.w_BTWebService.GetDomesticMatchNormalZRateStrRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://203.88.210.234:114/BaiTuoWeb.asmx")]
    public partial class GetDomesticMatchNormalZRateStrRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string xmlMessage;
        
        public GetDomesticMatchNormalZRateStrRequestBody() {
        }
        
        public GetDomesticMatchNormalZRateStrRequestBody(string xmlMessage) {
            this.xmlMessage = xmlMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDomesticMatchNormalZRateStrResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDomesticMatchNormalZRateStrResponse", Namespace="http://203.88.210.234:114/BaiTuoWeb.asmx", Order=0)]
        public PbProject.Logic.w_BTWebService.GetDomesticMatchNormalZRateStrResponseBody Body;
        
        public GetDomesticMatchNormalZRateStrResponse() {
        }
        
        public GetDomesticMatchNormalZRateStrResponse(PbProject.Logic.w_BTWebService.GetDomesticMatchNormalZRateStrResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://203.88.210.234:114/BaiTuoWeb.asmx")]
    public partial class GetDomesticMatchNormalZRateStrResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetDomesticMatchNormalZRateStrResult;
        
        public GetDomesticMatchNormalZRateStrResponseBody() {
        }
        
        public GetDomesticMatchNormalZRateStrResponseBody(string GetDomesticMatchNormalZRateStrResult) {
            this.GetDomesticMatchNormalZRateStrResult = GetDomesticMatchNormalZRateStrResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetInvalidationProviderListXMLRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetInvalidationProviderListXML", Namespace="http://203.88.210.234:114/BaiTuoWeb.asmx", Order=0)]
        public PbProject.Logic.w_BTWebService.GetInvalidationProviderListXMLRequestBody Body;
        
        public GetInvalidationProviderListXMLRequest() {
        }
        
        public GetInvalidationProviderListXMLRequest(PbProject.Logic.w_BTWebService.GetInvalidationProviderListXMLRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://203.88.210.234:114/BaiTuoWeb.asmx")]
    public partial class GetInvalidationProviderListXMLRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement xmlElement;
        
        public GetInvalidationProviderListXMLRequestBody() {
        }
        
        public GetInvalidationProviderListXMLRequestBody(System.Xml.Linq.XElement xmlElement) {
            this.xmlElement = xmlElement;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetInvalidationProviderListXMLResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetInvalidationProviderListXMLResponse", Namespace="http://203.88.210.234:114/BaiTuoWeb.asmx", Order=0)]
        public PbProject.Logic.w_BTWebService.GetInvalidationProviderListXMLResponseBody Body;
        
        public GetInvalidationProviderListXMLResponse() {
        }
        
        public GetInvalidationProviderListXMLResponse(PbProject.Logic.w_BTWebService.GetInvalidationProviderListXMLResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://203.88.210.234:114/BaiTuoWeb.asmx")]
    public partial class GetInvalidationProviderListXMLResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement GetInvalidationProviderListXMLResult;
        
        public GetInvalidationProviderListXMLResponseBody() {
        }
        
        public GetInvalidationProviderListXMLResponseBody(System.Xml.Linq.XElement GetInvalidationProviderListXMLResult) {
            this.GetInvalidationProviderListXMLResult = GetInvalidationProviderListXMLResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetInvalidationProviderListSTRRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetInvalidationProviderListSTR", Namespace="http://203.88.210.234:114/BaiTuoWeb.asmx", Order=0)]
        public PbProject.Logic.w_BTWebService.GetInvalidationProviderListSTRRequestBody Body;
        
        public GetInvalidationProviderListSTRRequest() {
        }
        
        public GetInvalidationProviderListSTRRequest(PbProject.Logic.w_BTWebService.GetInvalidationProviderListSTRRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://203.88.210.234:114/BaiTuoWeb.asmx")]
    public partial class GetInvalidationProviderListSTRRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string xmlDoc;
        
        public GetInvalidationProviderListSTRRequestBody() {
        }
        
        public GetInvalidationProviderListSTRRequestBody(string xmlDoc) {
            this.xmlDoc = xmlDoc;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetInvalidationProviderListSTRResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetInvalidationProviderListSTRResponse", Namespace="http://203.88.210.234:114/BaiTuoWeb.asmx", Order=0)]
        public PbProject.Logic.w_BTWebService.GetInvalidationProviderListSTRResponseBody Body;
        
        public GetInvalidationProviderListSTRResponse() {
        }
        
        public GetInvalidationProviderListSTRResponse(PbProject.Logic.w_BTWebService.GetInvalidationProviderListSTRResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://203.88.210.234:114/BaiTuoWeb.asmx")]
    public partial class GetInvalidationProviderListSTRResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetInvalidationProviderListSTRResult;
        
        public GetInvalidationProviderListSTRResponseBody() {
        }
        
        public GetInvalidationProviderListSTRResponseBody(string GetInvalidationProviderListSTRResult) {
            this.GetInvalidationProviderListSTRResult = GetInvalidationProviderListSTRResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class pnrCreateOrderExRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="pnrCreateOrderEx", Namespace="http://203.88.210.234:114/BaiTuoWeb.asmx", Order=0)]
        public PbProject.Logic.w_BTWebService.pnrCreateOrderExRequestBody Body;
        
        public pnrCreateOrderExRequest() {
        }
        
        public pnrCreateOrderExRequest(PbProject.Logic.w_BTWebService.pnrCreateOrderExRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://203.88.210.234:114/BaiTuoWeb.asmx")]
    public partial class pnrCreateOrderExRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement xeMessage;
        
        public pnrCreateOrderExRequestBody() {
        }
        
        public pnrCreateOrderExRequestBody(System.Xml.Linq.XElement xeMessage) {
            this.xeMessage = xeMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class pnrCreateOrderExResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="pnrCreateOrderExResponse", Namespace="http://203.88.210.234:114/BaiTuoWeb.asmx", Order=0)]
        public PbProject.Logic.w_BTWebService.pnrCreateOrderExResponseBody Body;
        
        public pnrCreateOrderExResponse() {
        }
        
        public pnrCreateOrderExResponse(PbProject.Logic.w_BTWebService.pnrCreateOrderExResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://203.88.210.234:114/BaiTuoWeb.asmx")]
    public partial class pnrCreateOrderExResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement pnrCreateOrderExResult;
        
        public pnrCreateOrderExResponseBody() {
        }
        
        public pnrCreateOrderExResponseBody(System.Xml.Linq.XElement pnrCreateOrderExResult) {
            this.pnrCreateOrderExResult = pnrCreateOrderExResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class pnrCreateOrderExStrRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="pnrCreateOrderExStr", Namespace="http://203.88.210.234:114/BaiTuoWeb.asmx", Order=0)]
        public PbProject.Logic.w_BTWebService.pnrCreateOrderExStrRequestBody Body;
        
        public pnrCreateOrderExStrRequest() {
        }
        
        public pnrCreateOrderExStrRequest(PbProject.Logic.w_BTWebService.pnrCreateOrderExStrRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://203.88.210.234:114/BaiTuoWeb.asmx")]
    public partial class pnrCreateOrderExStrRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string xeMessage;
        
        public pnrCreateOrderExStrRequestBody() {
        }
        
        public pnrCreateOrderExStrRequestBody(string xeMessage) {
            this.xeMessage = xeMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class pnrCreateOrderExStrResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="pnrCreateOrderExStrResponse", Namespace="http://203.88.210.234:114/BaiTuoWeb.asmx", Order=0)]
        public PbProject.Logic.w_BTWebService.pnrCreateOrderExStrResponseBody Body;
        
        public pnrCreateOrderExStrResponse() {
        }
        
        public pnrCreateOrderExStrResponse(PbProject.Logic.w_BTWebService.pnrCreateOrderExStrResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://203.88.210.234:114/BaiTuoWeb.asmx")]
    public partial class pnrCreateOrderExStrResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string pnrCreateOrderExStrResult;
        
        public pnrCreateOrderExStrResponseBody() {
        }
        
        public pnrCreateOrderExStrResponseBody(string pnrCreateOrderExStrResult) {
            this.pnrCreateOrderExStrResult = pnrCreateOrderExStrResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getOrderInfoXmlRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getOrderInfoXml", Namespace="http://203.88.210.234:114/BaiTuoWeb.asmx", Order=0)]
        public PbProject.Logic.w_BTWebService.getOrderInfoXmlRequestBody Body;
        
        public getOrderInfoXmlRequest() {
        }
        
        public getOrderInfoXmlRequest(PbProject.Logic.w_BTWebService.getOrderInfoXmlRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://203.88.210.234:114/BaiTuoWeb.asmx")]
    public partial class getOrderInfoXmlRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement xmlMessage;
        
        public getOrderInfoXmlRequestBody() {
        }
        
        public getOrderInfoXmlRequestBody(System.Xml.Linq.XElement xmlMessage) {
            this.xmlMessage = xmlMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getOrderInfoXmlResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getOrderInfoXmlResponse", Namespace="http://203.88.210.234:114/BaiTuoWeb.asmx", Order=0)]
        public PbProject.Logic.w_BTWebService.getOrderInfoXmlResponseBody Body;
        
        public getOrderInfoXmlResponse() {
        }
        
        public getOrderInfoXmlResponse(PbProject.Logic.w_BTWebService.getOrderInfoXmlResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://203.88.210.234:114/BaiTuoWeb.asmx")]
    public partial class getOrderInfoXmlResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement getOrderInfoXmlResult;
        
        public getOrderInfoXmlResponseBody() {
        }
        
        public getOrderInfoXmlResponseBody(System.Xml.Linq.XElement getOrderInfoXmlResult) {
            this.getOrderInfoXmlResult = getOrderInfoXmlResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class NotifyXmlRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="NotifyXml", Namespace="http://203.88.210.234:114/BaiTuoWeb.asmx", Order=0)]
        public PbProject.Logic.w_BTWebService.NotifyXmlRequestBody Body;
        
        public NotifyXmlRequest() {
        }
        
        public NotifyXmlRequest(PbProject.Logic.w_BTWebService.NotifyXmlRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://203.88.210.234:114/BaiTuoWeb.asmx")]
    public partial class NotifyXmlRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement XmlMessage;
        
        public NotifyXmlRequestBody() {
        }
        
        public NotifyXmlRequestBody(System.Xml.Linq.XElement XmlMessage) {
            this.XmlMessage = XmlMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class NotifyXmlResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="NotifyXmlResponse", Namespace="http://203.88.210.234:114/BaiTuoWeb.asmx", Order=0)]
        public PbProject.Logic.w_BTWebService.NotifyXmlResponseBody Body;
        
        public NotifyXmlResponse() {
        }
        
        public NotifyXmlResponse(PbProject.Logic.w_BTWebService.NotifyXmlResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class NotifyXmlResponseBody {
        
        public NotifyXmlResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class NotifyStrRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="NotifyStr", Namespace="http://203.88.210.234:114/BaiTuoWeb.asmx", Order=0)]
        public PbProject.Logic.w_BTWebService.NotifyStrRequestBody Body;
        
        public NotifyStrRequest() {
        }
        
        public NotifyStrRequest(PbProject.Logic.w_BTWebService.NotifyStrRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://203.88.210.234:114/BaiTuoWeb.asmx")]
    public partial class NotifyStrRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Message;
        
        public NotifyStrRequestBody() {
        }
        
        public NotifyStrRequestBody(string Message) {
            this.Message = Message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class NotifyStrResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="NotifyStrResponse", Namespace="http://203.88.210.234:114/BaiTuoWeb.asmx", Order=0)]
        public PbProject.Logic.w_BTWebService.NotifyStrResponseBody Body;
        
        public NotifyStrResponse() {
        }
        
        public NotifyStrResponse(PbProject.Logic.w_BTWebService.NotifyStrResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class NotifyStrResponseBody {
        
        public NotifyStrResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ApplyRefundOrderRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ApplyRefundOrder", Namespace="http://203.88.210.234:114/BaiTuoWeb.asmx", Order=0)]
        public PbProject.Logic.w_BTWebService.ApplyRefundOrderRequestBody Body;
        
        public ApplyRefundOrderRequest() {
        }
        
        public ApplyRefundOrderRequest(PbProject.Logic.w_BTWebService.ApplyRefundOrderRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://203.88.210.234:114/BaiTuoWeb.asmx")]
    public partial class ApplyRefundOrderRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement xml;
        
        public ApplyRefundOrderRequestBody() {
        }
        
        public ApplyRefundOrderRequestBody(System.Xml.Linq.XElement xml) {
            this.xml = xml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ApplyRefundOrderResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ApplyRefundOrderResponse", Namespace="http://203.88.210.234:114/BaiTuoWeb.asmx", Order=0)]
        public PbProject.Logic.w_BTWebService.ApplyRefundOrderResponseBody Body;
        
        public ApplyRefundOrderResponse() {
        }
        
        public ApplyRefundOrderResponse(PbProject.Logic.w_BTWebService.ApplyRefundOrderResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://203.88.210.234:114/BaiTuoWeb.asmx")]
    public partial class ApplyRefundOrderResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement ApplyRefundOrderResult;
        
        public ApplyRefundOrderResponseBody() {
        }
        
        public ApplyRefundOrderResponseBody(System.Xml.Linq.XElement ApplyRefundOrderResult) {
            this.ApplyRefundOrderResult = ApplyRefundOrderResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ApplyRefundOrderStrRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ApplyRefundOrderStr", Namespace="http://203.88.210.234:114/BaiTuoWeb.asmx", Order=0)]
        public PbProject.Logic.w_BTWebService.ApplyRefundOrderStrRequestBody Body;
        
        public ApplyRefundOrderStrRequest() {
        }
        
        public ApplyRefundOrderStrRequest(PbProject.Logic.w_BTWebService.ApplyRefundOrderStrRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://203.88.210.234:114/BaiTuoWeb.asmx")]
    public partial class ApplyRefundOrderStrRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Message;
        
        public ApplyRefundOrderStrRequestBody() {
        }
        
        public ApplyRefundOrderStrRequestBody(string Message) {
            this.Message = Message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ApplyRefundOrderStrResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ApplyRefundOrderStrResponse", Namespace="http://203.88.210.234:114/BaiTuoWeb.asmx", Order=0)]
        public PbProject.Logic.w_BTWebService.ApplyRefundOrderStrResponseBody Body;
        
        public ApplyRefundOrderStrResponse() {
        }
        
        public ApplyRefundOrderStrResponse(PbProject.Logic.w_BTWebService.ApplyRefundOrderStrResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://203.88.210.234:114/BaiTuoWeb.asmx")]
    public partial class ApplyRefundOrderStrResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ApplyRefundOrderStrResult;
        
        public ApplyRefundOrderStrResponseBody() {
        }
        
        public ApplyRefundOrderStrResponseBody(string ApplyRefundOrderStrResult) {
            this.ApplyRefundOrderStrResult = ApplyRefundOrderStrResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUrlDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUrlData", Namespace="http://203.88.210.234:114/BaiTuoWeb.asmx", Order=0)]
        public PbProject.Logic.w_BTWebService.GetUrlDataRequestBody Body;
        
        public GetUrlDataRequest() {
        }
        
        public GetUrlDataRequest(PbProject.Logic.w_BTWebService.GetUrlDataRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://203.88.210.234:114/BaiTuoWeb.asmx")]
    public partial class GetUrlDataRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string url;
        
        public GetUrlDataRequestBody() {
        }
        
        public GetUrlDataRequestBody(string url) {
            this.url = url;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUrlDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUrlDataResponse", Namespace="http://203.88.210.234:114/BaiTuoWeb.asmx", Order=0)]
        public PbProject.Logic.w_BTWebService.GetUrlDataResponseBody Body;
        
        public GetUrlDataResponse() {
        }
        
        public GetUrlDataResponse(PbProject.Logic.w_BTWebService.GetUrlDataResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://203.88.210.234:114/BaiTuoWeb.asmx")]
    public partial class GetUrlDataResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetUrlDataResult;
        
        public GetUrlDataResponseBody() {
        }
        
        public GetUrlDataResponseBody(string GetUrlDataResult) {
            this.GetUrlDataResult = GetUrlDataResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BaiTuoWebSoapChannel : PbProject.Logic.w_BTWebService.BaiTuoWebSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BaiTuoWebSoapClient : System.ServiceModel.ClientBase<PbProject.Logic.w_BTWebService.BaiTuoWebSoap>, PbProject.Logic.w_BTWebService.BaiTuoWebSoap {
        
        public BaiTuoWebSoapClient() {
        }
        
        public BaiTuoWebSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BaiTuoWebSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BaiTuoWebSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BaiTuoWebSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PbProject.Logic.w_BTWebService.GetAlterDomesticCabinZRateByParamResponse PbProject.Logic.w_BTWebService.BaiTuoWebSoap.GetAlterDomesticCabinZRateByParam(PbProject.Logic.w_BTWebService.GetAlterDomesticCabinZRateByParamRequest request) {
            return base.Channel.GetAlterDomesticCabinZRateByParam(request);
        }
        
        public System.Xml.Linq.XElement GetAlterDomesticCabinZRateByParam(string TripType, string TicketType, string CoAgentOffice, string CoUserName, string CoUserPwd, string RQStartDateTime) {
            PbProject.Logic.w_BTWebService.GetAlterDomesticCabinZRateByParamRequest inValue = new PbProject.Logic.w_BTWebService.GetAlterDomesticCabinZRateByParamRequest();
            inValue.Body = new PbProject.Logic.w_BTWebService.GetAlterDomesticCabinZRateByParamRequestBody();
            inValue.Body.TripType = TripType;
            inValue.Body.TicketType = TicketType;
            inValue.Body.CoAgentOffice = CoAgentOffice;
            inValue.Body.CoUserName = CoUserName;
            inValue.Body.CoUserPwd = CoUserPwd;
            inValue.Body.RQStartDateTime = RQStartDateTime;
            PbProject.Logic.w_BTWebService.GetAlterDomesticCabinZRateByParamResponse retVal = ((PbProject.Logic.w_BTWebService.BaiTuoWebSoap)(this)).GetAlterDomesticCabinZRateByParam(inValue);
            return retVal.Body.GetAlterDomesticCabinZRateByParamResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PbProject.Logic.w_BTWebService.GetAlterDomesticCabinZRateByXmlResponse PbProject.Logic.w_BTWebService.BaiTuoWebSoap.GetAlterDomesticCabinZRateByXml(PbProject.Logic.w_BTWebService.GetAlterDomesticCabinZRateByXmlRequest request) {
            return base.Channel.GetAlterDomesticCabinZRateByXml(request);
        }
        
        public System.Xml.Linq.XElement GetAlterDomesticCabinZRateByXml(System.Xml.Linq.XElement xmlMessage) {
            PbProject.Logic.w_BTWebService.GetAlterDomesticCabinZRateByXmlRequest inValue = new PbProject.Logic.w_BTWebService.GetAlterDomesticCabinZRateByXmlRequest();
            inValue.Body = new PbProject.Logic.w_BTWebService.GetAlterDomesticCabinZRateByXmlRequestBody();
            inValue.Body.xmlMessage = xmlMessage;
            PbProject.Logic.w_BTWebService.GetAlterDomesticCabinZRateByXmlResponse retVal = ((PbProject.Logic.w_BTWebService.BaiTuoWebSoap)(this)).GetAlterDomesticCabinZRateByXml(inValue);
            return retVal.Body.GetAlterDomesticCabinZRateByXmlResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PbProject.Logic.w_BTWebService.GetDomesticMatchNormalZRateListResponse PbProject.Logic.w_BTWebService.BaiTuoWebSoap.GetDomesticMatchNormalZRateList(PbProject.Logic.w_BTWebService.GetDomesticMatchNormalZRateListRequest request) {
            return base.Channel.GetDomesticMatchNormalZRateList(request);
        }
        
        public System.Xml.Linq.XElement GetDomesticMatchNormalZRateList(System.Xml.Linq.XElement xmlMessage) {
            PbProject.Logic.w_BTWebService.GetDomesticMatchNormalZRateListRequest inValue = new PbProject.Logic.w_BTWebService.GetDomesticMatchNormalZRateListRequest();
            inValue.Body = new PbProject.Logic.w_BTWebService.GetDomesticMatchNormalZRateListRequestBody();
            inValue.Body.xmlMessage = xmlMessage;
            PbProject.Logic.w_BTWebService.GetDomesticMatchNormalZRateListResponse retVal = ((PbProject.Logic.w_BTWebService.BaiTuoWebSoap)(this)).GetDomesticMatchNormalZRateList(inValue);
            return retVal.Body.GetDomesticMatchNormalZRateListResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PbProject.Logic.w_BTWebService.GetDomesticMatchNormalZRateStrResponse PbProject.Logic.w_BTWebService.BaiTuoWebSoap.GetDomesticMatchNormalZRateStr(PbProject.Logic.w_BTWebService.GetDomesticMatchNormalZRateStrRequest request) {
            return base.Channel.GetDomesticMatchNormalZRateStr(request);
        }
        
        public string GetDomesticMatchNormalZRateStr(string xmlMessage) {
            PbProject.Logic.w_BTWebService.GetDomesticMatchNormalZRateStrRequest inValue = new PbProject.Logic.w_BTWebService.GetDomesticMatchNormalZRateStrRequest();
            inValue.Body = new PbProject.Logic.w_BTWebService.GetDomesticMatchNormalZRateStrRequestBody();
            inValue.Body.xmlMessage = xmlMessage;
            PbProject.Logic.w_BTWebService.GetDomesticMatchNormalZRateStrResponse retVal = ((PbProject.Logic.w_BTWebService.BaiTuoWebSoap)(this)).GetDomesticMatchNormalZRateStr(inValue);
            return retVal.Body.GetDomesticMatchNormalZRateStrResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PbProject.Logic.w_BTWebService.GetInvalidationProviderListXMLResponse PbProject.Logic.w_BTWebService.BaiTuoWebSoap.GetInvalidationProviderListXML(PbProject.Logic.w_BTWebService.GetInvalidationProviderListXMLRequest request) {
            return base.Channel.GetInvalidationProviderListXML(request);
        }
        
        public System.Xml.Linq.XElement GetInvalidationProviderListXML(System.Xml.Linq.XElement xmlElement) {
            PbProject.Logic.w_BTWebService.GetInvalidationProviderListXMLRequest inValue = new PbProject.Logic.w_BTWebService.GetInvalidationProviderListXMLRequest();
            inValue.Body = new PbProject.Logic.w_BTWebService.GetInvalidationProviderListXMLRequestBody();
            inValue.Body.xmlElement = xmlElement;
            PbProject.Logic.w_BTWebService.GetInvalidationProviderListXMLResponse retVal = ((PbProject.Logic.w_BTWebService.BaiTuoWebSoap)(this)).GetInvalidationProviderListXML(inValue);
            return retVal.Body.GetInvalidationProviderListXMLResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PbProject.Logic.w_BTWebService.GetInvalidationProviderListSTRResponse PbProject.Logic.w_BTWebService.BaiTuoWebSoap.GetInvalidationProviderListSTR(PbProject.Logic.w_BTWebService.GetInvalidationProviderListSTRRequest request) {
            return base.Channel.GetInvalidationProviderListSTR(request);
        }
        
        public string GetInvalidationProviderListSTR(string xmlDoc) {
            PbProject.Logic.w_BTWebService.GetInvalidationProviderListSTRRequest inValue = new PbProject.Logic.w_BTWebService.GetInvalidationProviderListSTRRequest();
            inValue.Body = new PbProject.Logic.w_BTWebService.GetInvalidationProviderListSTRRequestBody();
            inValue.Body.xmlDoc = xmlDoc;
            PbProject.Logic.w_BTWebService.GetInvalidationProviderListSTRResponse retVal = ((PbProject.Logic.w_BTWebService.BaiTuoWebSoap)(this)).GetInvalidationProviderListSTR(inValue);
            return retVal.Body.GetInvalidationProviderListSTRResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PbProject.Logic.w_BTWebService.pnrCreateOrderExResponse PbProject.Logic.w_BTWebService.BaiTuoWebSoap.pnrCreateOrderEx(PbProject.Logic.w_BTWebService.pnrCreateOrderExRequest request) {
            return base.Channel.pnrCreateOrderEx(request);
        }
        
        public System.Xml.Linq.XElement pnrCreateOrderEx(System.Xml.Linq.XElement xeMessage) {
            PbProject.Logic.w_BTWebService.pnrCreateOrderExRequest inValue = new PbProject.Logic.w_BTWebService.pnrCreateOrderExRequest();
            inValue.Body = new PbProject.Logic.w_BTWebService.pnrCreateOrderExRequestBody();
            inValue.Body.xeMessage = xeMessage;
            PbProject.Logic.w_BTWebService.pnrCreateOrderExResponse retVal = ((PbProject.Logic.w_BTWebService.BaiTuoWebSoap)(this)).pnrCreateOrderEx(inValue);
            return retVal.Body.pnrCreateOrderExResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PbProject.Logic.w_BTWebService.pnrCreateOrderExStrResponse PbProject.Logic.w_BTWebService.BaiTuoWebSoap.pnrCreateOrderExStr(PbProject.Logic.w_BTWebService.pnrCreateOrderExStrRequest request) {
            return base.Channel.pnrCreateOrderExStr(request);
        }
        
        public string pnrCreateOrderExStr(string xeMessage) {
            PbProject.Logic.w_BTWebService.pnrCreateOrderExStrRequest inValue = new PbProject.Logic.w_BTWebService.pnrCreateOrderExStrRequest();
            inValue.Body = new PbProject.Logic.w_BTWebService.pnrCreateOrderExStrRequestBody();
            inValue.Body.xeMessage = xeMessage;
            PbProject.Logic.w_BTWebService.pnrCreateOrderExStrResponse retVal = ((PbProject.Logic.w_BTWebService.BaiTuoWebSoap)(this)).pnrCreateOrderExStr(inValue);
            return retVal.Body.pnrCreateOrderExStrResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PbProject.Logic.w_BTWebService.getOrderInfoXmlResponse PbProject.Logic.w_BTWebService.BaiTuoWebSoap.getOrderInfoXml(PbProject.Logic.w_BTWebService.getOrderInfoXmlRequest request) {
            return base.Channel.getOrderInfoXml(request);
        }
        
        public System.Xml.Linq.XElement getOrderInfoXml(System.Xml.Linq.XElement xmlMessage) {
            PbProject.Logic.w_BTWebService.getOrderInfoXmlRequest inValue = new PbProject.Logic.w_BTWebService.getOrderInfoXmlRequest();
            inValue.Body = new PbProject.Logic.w_BTWebService.getOrderInfoXmlRequestBody();
            inValue.Body.xmlMessage = xmlMessage;
            PbProject.Logic.w_BTWebService.getOrderInfoXmlResponse retVal = ((PbProject.Logic.w_BTWebService.BaiTuoWebSoap)(this)).getOrderInfoXml(inValue);
            return retVal.Body.getOrderInfoXmlResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PbProject.Logic.w_BTWebService.NotifyXmlResponse PbProject.Logic.w_BTWebService.BaiTuoWebSoap.NotifyXml(PbProject.Logic.w_BTWebService.NotifyXmlRequest request) {
            return base.Channel.NotifyXml(request);
        }
        
        public void NotifyXml(System.Xml.Linq.XElement XmlMessage) {
            PbProject.Logic.w_BTWebService.NotifyXmlRequest inValue = new PbProject.Logic.w_BTWebService.NotifyXmlRequest();
            inValue.Body = new PbProject.Logic.w_BTWebService.NotifyXmlRequestBody();
            inValue.Body.XmlMessage = XmlMessage;
            PbProject.Logic.w_BTWebService.NotifyXmlResponse retVal = ((PbProject.Logic.w_BTWebService.BaiTuoWebSoap)(this)).NotifyXml(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PbProject.Logic.w_BTWebService.NotifyStrResponse PbProject.Logic.w_BTWebService.BaiTuoWebSoap.NotifyStr(PbProject.Logic.w_BTWebService.NotifyStrRequest request) {
            return base.Channel.NotifyStr(request);
        }
        
        public void NotifyStr(string Message) {
            PbProject.Logic.w_BTWebService.NotifyStrRequest inValue = new PbProject.Logic.w_BTWebService.NotifyStrRequest();
            inValue.Body = new PbProject.Logic.w_BTWebService.NotifyStrRequestBody();
            inValue.Body.Message = Message;
            PbProject.Logic.w_BTWebService.NotifyStrResponse retVal = ((PbProject.Logic.w_BTWebService.BaiTuoWebSoap)(this)).NotifyStr(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PbProject.Logic.w_BTWebService.ApplyRefundOrderResponse PbProject.Logic.w_BTWebService.BaiTuoWebSoap.ApplyRefundOrder(PbProject.Logic.w_BTWebService.ApplyRefundOrderRequest request) {
            return base.Channel.ApplyRefundOrder(request);
        }
        
        public System.Xml.Linq.XElement ApplyRefundOrder(System.Xml.Linq.XElement xml) {
            PbProject.Logic.w_BTWebService.ApplyRefundOrderRequest inValue = new PbProject.Logic.w_BTWebService.ApplyRefundOrderRequest();
            inValue.Body = new PbProject.Logic.w_BTWebService.ApplyRefundOrderRequestBody();
            inValue.Body.xml = xml;
            PbProject.Logic.w_BTWebService.ApplyRefundOrderResponse retVal = ((PbProject.Logic.w_BTWebService.BaiTuoWebSoap)(this)).ApplyRefundOrder(inValue);
            return retVal.Body.ApplyRefundOrderResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PbProject.Logic.w_BTWebService.ApplyRefundOrderStrResponse PbProject.Logic.w_BTWebService.BaiTuoWebSoap.ApplyRefundOrderStr(PbProject.Logic.w_BTWebService.ApplyRefundOrderStrRequest request) {
            return base.Channel.ApplyRefundOrderStr(request);
        }
        
        public string ApplyRefundOrderStr(string Message) {
            PbProject.Logic.w_BTWebService.ApplyRefundOrderStrRequest inValue = new PbProject.Logic.w_BTWebService.ApplyRefundOrderStrRequest();
            inValue.Body = new PbProject.Logic.w_BTWebService.ApplyRefundOrderStrRequestBody();
            inValue.Body.Message = Message;
            PbProject.Logic.w_BTWebService.ApplyRefundOrderStrResponse retVal = ((PbProject.Logic.w_BTWebService.BaiTuoWebSoap)(this)).ApplyRefundOrderStr(inValue);
            return retVal.Body.ApplyRefundOrderStrResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PbProject.Logic.w_BTWebService.GetUrlDataResponse PbProject.Logic.w_BTWebService.BaiTuoWebSoap.GetUrlData(PbProject.Logic.w_BTWebService.GetUrlDataRequest request) {
            return base.Channel.GetUrlData(request);
        }
        
        public string GetUrlData(string url) {
            PbProject.Logic.w_BTWebService.GetUrlDataRequest inValue = new PbProject.Logic.w_BTWebService.GetUrlDataRequest();
            inValue.Body = new PbProject.Logic.w_BTWebService.GetUrlDataRequestBody();
            inValue.Body.url = url;
            PbProject.Logic.w_BTWebService.GetUrlDataResponse retVal = ((PbProject.Logic.w_BTWebService.BaiTuoWebSoap)(this)).GetUrlData(inValue);
            return retVal.Body.GetUrlDataResult;
        }
    }
}
