//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.239
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PbProject.Logic.w_8000YService {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="w_8000YService.W8000YServiceSoap")]
    public interface W8000YServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AlreadyDisposalSynchronizationNew_All", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet AlreadyDisposalSynchronizationNew_All(string name, string pwd, string datetime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDeletePolicy", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetDeletePolicy(string name, string pwd, string datetime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SPbyPNRNote", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet SPbyPNRNote(string name, string pwd, string pnrCode, int isSpecial, string pnrInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreatOrderNewByPNRNote", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet CreatOrderNewByPNRNote(string name, string pwd, string pnrCode, string pid, string pnrInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/OrderPayOutTicketAndPly", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet OrderPayOutTicketAndPly(string name, string pwd, string ordertime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PaySignOn", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string PaySignOn(string name, string pwd, string emAccount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AutomatismPay", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet AutomatismPay(string name, string pwd, string orderguid, string payAccount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetWhyByOrder", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetWhyByOrder(string name, string pwd, string type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/OrderRGIInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string OrderRGIInfo(string name, string pwd, string porderguid, string ticketNo, string whyId, string type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReturnTicekNo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ReturnTicekNo(string name, string pwd, string orderid);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface W8000YServiceSoapChannel : PbProject.Logic.w_8000YService.W8000YServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class W8000YServiceSoapClient : System.ServiceModel.ClientBase<PbProject.Logic.w_8000YService.W8000YServiceSoap>, PbProject.Logic.w_8000YService.W8000YServiceSoap {
        
        public W8000YServiceSoapClient() {
        }
        
        public W8000YServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public W8000YServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public W8000YServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public W8000YServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet AlreadyDisposalSynchronizationNew_All(string name, string pwd, string datetime) {
            return base.Channel.AlreadyDisposalSynchronizationNew_All(name, pwd, datetime);
        }
        
        public System.Data.DataSet GetDeletePolicy(string name, string pwd, string datetime) {
            return base.Channel.GetDeletePolicy(name, pwd, datetime);
        }
        
        public System.Data.DataSet SPbyPNRNote(string name, string pwd, string pnrCode, int isSpecial, string pnrInfo) {
            return base.Channel.SPbyPNRNote(name, pwd, pnrCode, isSpecial, pnrInfo);
        }
        
        public System.Data.DataSet CreatOrderNewByPNRNote(string name, string pwd, string pnrCode, string pid, string pnrInfo) {
            return base.Channel.CreatOrderNewByPNRNote(name, pwd, pnrCode, pid, pnrInfo);
        }
        
        public System.Data.DataSet OrderPayOutTicketAndPly(string name, string pwd, string ordertime) {
            return base.Channel.OrderPayOutTicketAndPly(name, pwd, ordertime);
        }
        
        public string PaySignOn(string name, string pwd, string emAccount) {
            return base.Channel.PaySignOn(name, pwd, emAccount);
        }
        
        public System.Data.DataSet AutomatismPay(string name, string pwd, string orderguid, string payAccount) {
            return base.Channel.AutomatismPay(name, pwd, orderguid, payAccount);
        }
        
        public System.Data.DataSet GetWhyByOrder(string name, string pwd, string type) {
            return base.Channel.GetWhyByOrder(name, pwd, type);
        }
        
        public string OrderRGIInfo(string name, string pwd, string porderguid, string ticketNo, string whyId, string type) {
            return base.Channel.OrderRGIInfo(name, pwd, porderguid, ticketNo, whyId, type);
        }
        
        public System.Data.DataSet ReturnTicekNo(string name, string pwd, string orderid) {
            return base.Channel.ReturnTicekNo(name, pwd, orderid);
        }
    }
}
